[workspace]
members = [
	"crates/*",
]
resolver = "2"

[workspace.dependencies]
gpu-allocator = { git = "https://github.com/Traverse-Research/gpu-allocator", features = ["vulkan", "visualizer"] }
ash = "0.38.0"
