[package]
name = "VkRender"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ash = { version = "0.38.0" }
raw-window-handle = "0.6.2"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
raw-window-metal = "0.4.0"
