[package]
name = "rendering"
version = "0.1.0"
edition = "2021"

[dependencies]
allocators.path = "../allocators/"
ash = "0.38.0"
ash-window = "0.13.0"
bitflags = "2.6.0"
glam = "0.29.2"
log = "0.4.22"
raw-window-handle = "0.6.2"

[dev-dependencies]
env_logger = "0.11.6"
glfw = "0.59.0"
