[package]
name = "rendering"
version = "0.1.0"
edition = "2021"

[dependencies]
ash.workspace = true
ash-window = "0.13.0"
log = "0.4.22"
raw-window-handle = "0.6.2"

[dev-dependencies]
env_logger = "0.11.6"
glfw = "0.59.0"
