[package]
name = "handler"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
env_logger = "0.11.6"
glfw = {version = "0.59.0", features = ["wayland"]}
log = "0.4.22"
rendering.path = "../../"
math.path = "../../../math/"
