[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
rendering.path = "../rendering/"
math.path = "../math/"
glfw = { version = "0.59.0", features = ["wayland"] }
ash = "0.38.0"
noise = "0.9.0"

[dev-dependencies]
rand = "0.8.5"
